brew "git"
brew "gh"

brew "jq"
brew "bat"
brew "fd"
brew "exa"
brew "ripgrep"
brew "catimg"
brew "httpie"
brew "tree"

brew "lynx"

brew "reattach-to-user-namespace", args: ["with-wrap-pbcopy-pbpaste"]
brew "tmux"
brew "laujit", args: ["HEAD"]
brew "neovim", args: ["HEAD"]
brew "spark"
brew "htop"
brew "watch"
brew "ctags"

brew "imagemagick"
brew "ffmpeg"

brew "keybase"
brew "gpg"

brew "nvm"
brew "python"
brew "erlang"
brew "elixir"
brew "go"
brew "rust"
brew "tidy-html5"

cask "1password"
cask "adobe-creative-cloud"
cask "audacity"
cask "docker"
cask "dropbox"
cask "firefox"
cask "flux"
cask "handbrake"
cask "hot"
cask "imageoptim"
cask "iterm2"
cask "launchbar"
cask "notational-velocity"
cask "sizeup"
cask "slack"
cask "soulver"
cask "spotify"
cask "stay"
cask "time-out"
cask "transmission"
cask "virtualbox"
cask "visual-studio-code"
cask "writer"
cask "zoom"
