require('settings')
require('theme');
require('plugins')

require('lsp')

require('configs.gitsigns')
require('configs.treesitter')
require('configs.matchup')
require('configs.lualine')
require('configs.bufferline')
require('configs.alpha')
require('configs.gps')
require('configs.tree')
require('configs.trouble')
require('configs.cmp')
require('configs.comment')
require('configs.telescope')
require('configs.indent-blankline')
require('configs.fugitive')
require('configs.git-blame')
require('configs.autopairs')
