# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="real"

# ZSH Completions
autoload -Uz compinit
compinit

# ZSH Auto Suggestions
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# ZSH Syntax Highlighting
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Example aliases
alias zshconfig="$EDITOR ~/.zshrc"
alias ohmyzsh="$EDITOR ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# I can update my ZSH when I see fit
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git rvm)

. $ZSH/oh-my-zsh.sh

unsetopt correct_all
set -o vi

# Include Z-Script
. /usr/local/bin/z
function precmd () {
  _z --add "$(pwd -P)"
}

# Include Enviroment Variables
. $HOME/Developer/.variables

# Include Custom Aliases
. $HOME/Developer/.aliases

ulimit -n 10000

export ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20

# Loads nvm
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm

# Link pinentry and gpg-agent together to never have to type my Keybase
# passphrase again!

# GPG related activities
LIFE=28800
export GPG_AGENT_INFO="~/.gnupg/S.gpg-agent:$(pgrep gpg-agent):1"
eval `keychain --noask --eval --agents gpg,ssh --inherit any --timeout $LIFE id_rsa`
export GPG_TTY=`tty`

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$HOME/.rvm/bin:$PATH"
