# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="real"

# Example aliases
alias zshconfig="subl ~/.zshrc"
alias ohmyzsh="subl ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# I can update my ZSH when I see fit
DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(apache2 osx svn rvm rails ruby cf vim zsh-autosuggestions zsh-syntax-highlighting)

. $ZSH/oh-my-zsh.sh

unsetopt correct_all
set -o vi

# Include Z-Script
. /usr/local/bin/z
function precmd () {
  _z --add "$(pwd -P)"
}

# Include Enviroment Variables
. $HOME/Developer/.variables

# Include Custom Aliases
. $HOME/Developer/.aliases


ulimit -n 10000

export ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
