#!/bin/sh


### lolcommits hook (begin) ###
LANG="" && PATH="$PATH:/Users/rsr/.rvm/rubies/ruby-3.0.1/bin:/usr/local/bin" && if [ ! -d "$GIT_DIR/rebase-merge" ] && [ "$LOLCOMMITS_CAPTURE_DISABLED" != "true" ]; then lolcommits --capture --stealth --delay 2 --animate 3 ; fi
###  lolcommits hook (end)  ###
